import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import {SidebarProvider} from "@/src/app/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {

    return (
    <html lang="en" className={``} data-bs-theme="dark">
      <body>
      <div className={`d-flex`} style={{
          minHeight:'100dvh'
      }}>
          <SidebarProvider />
      {children}
      </div>
      </body>
    </html>
  );
}
